import {
    ROUTING_CREATE,
    ROUTING_LOGIN,
    ROUTING_LOGOUT,
    ROUTING_RATINGS,
    ROUTING_REGISTRATION
} from "./RoutingConstants";

export const WEBSITE_ROUTING_INDEX: string = "/";
export const WEBSITE_ROUTING_LOGIN: string = ROUTING_LOGIN;
export const WEBSITE_ROUTING_LOGOUT: string = ROUTING_LOGOUT;
export const WEBSITE_ROUTING_REGISTRATION: string = ROUTING_REGISTRATION;
export const WEBSITE_ROUTING_RATINGS_CREATE: string = ROUTING_RATINGS + ROUTING_CREATE;
export const WEBSITE_ROUTING_NOT_FOUND: string = "*";